### ISSUE TITLE
Schönes Projekt

### ISSUE THREAD

**Issue by ghost** [Jugendhackt/HowToPGP#8]
Hallo Jugendhackt,

schönes Projekt was ihr da auf die Beine gestellt habt, schaue mich gerade noch ein bisschen um und klicke die verschiedenen Anleitungen durch.
Dabei sind mir drei kleine Tippfehler aufgefallen.

Einmal unter 
"http://www.tools.bytehamster.com/HowToPGP/index.php?page=description&os=windows&client=browser&level=1&browser=firefox" und zwar bei der Textpassage 

_In diesem Artikel von Chip Praxistipps findest du mehr Informationen zu den Vor- und Nachteilen der beiden Internentbrowsern.In diesem Artikel von Chip Praxistipps findest du mehr Informationen zu den Vor- und Nachteilen der beiden *_Internentbrowsern**.\* und dann noch bei der nächsten Überschift _Installation des *_Mailbelope**-Plugins*

Außerdem gibt es noch einen kleinen Tippfehler unter
"http://www.tools.bytehamster.com/HowToPGP/index.php?page=description&os=linux&client=thunderbird&level=3&browser="

und zwar in der Überschrift _Wie funktioniert *_asymmertische*\* Verschlüsselung*
falls mir noch was auffällt, lasse ich es euch wissen. 

Ansonsten weiter so!
Beste Grüße

pete13

**Comment by two-heart** [comment]
Vielen Dank für dein Feedback und deine Arbeit! Du hast uns sehr geholfen unsere Seite zu verbessern.
